export const ORDER = 'ORDER';
export const LOAD_COUNTRIES = 'LOAD_COUNTRIES';
export const CHANGE_PAGE = "CHANGE_PAGE";
export const ORDER_POPULATION = 'ORDER_POPULATION';
export const ORDER_ALPHABETICAl = 'ORDER_ALPHABETICAl';
export const COUNTRIES_FILTER = 'COUNTRIES_FILTER';